'use strict';
const paths={windows:'<path d="M3 5l8-1v7H3zM13 4l8-1v8h-8zM3 13h8v7l-8-1zM13 13h8v8l-8-1z" fill="currentColor" stroke="none"/>',play:'<path d="m8 5 11 7-11 7z"/>',screen:'<rect x="3" y="3" width="18" height="14" rx="2"/><path d="M12 17v4M8 21h8"/>',phone:'<rect x="7" y="2" width="10" height="20" rx="3"/><path d="M11 18h2"/>',zoom:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6M7 10h6M10 7v6"/>',text:'<path d="M4 5h16M4 5v3M20 5v3M12 5v15M8 20h8"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/>',expand:'<path d="M9 3H3v6M15 3h6v6M21 15v6h-6M9 21H3v-6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',camera:'<rect x="3" y="5" width="12" height="14" rx="3"/><path d="m15 9 6-3v12l-6-3"/>',mic:'<rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/>',spark:'<path d="m12 3 2.7 6.3L21 12l-6.3 2.7L12 21l-2.7-6.3L3 12l6.3-2.7z"/>',prompt:'<rect x="3" y="4" width="18" height="14" rx="2"/><path d="M7 8h10M7 12h6M12 18v3M8 21h8"/>',keyboard:'<rect x="2" y="5" width="20" height="14" rx="3"/><path d="M6 9h.1M10 9h.1M14 9h.1M18 9h.1M6 13h.1M10 13h.1M14 13h.1M18 13h.1M8 16h8"/>',folder:'<path d="M3 7V5a2 2 0 0 1 2-2h4l3 4h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>',pause:'<path d="M9 5v14M15 5v14"/>',check:'<path d="m5 12 4 4L19 6"/>',sliders:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2" fill="#111219"/><circle cx="15" cy="12" r="2" fill="#111219"/><circle cx="8" cy="18" r="2" fill="#111219"/>',plus:'<path d="M12 5v14M5 12h14"/>',record:'<circle cx="12" cy="12" r="7" fill="currentColor" stroke="none"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>'};
function renderIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[el.dataset.icon]||paths.spark}</svg>`;});}
renderIcons();
paths.refresh='<path d="M3 10a9 9 0 0 1 15-6l3 3M21 3v4h-4M21 14a9 9 0 0 1-15 6l-3-3M3 21v-4h4"/>';
renderIcons();
const imageDialog=document.querySelector('#image-dialog');
document.addEventListener('click',event=>{const shot=event.target.closest('[data-image]');if(shot){document.querySelector('#expanded-image').src=shot.dataset.image;document.querySelector('#expanded-image').alt=shot.dataset.caption;document.querySelector('#image-caption').textContent=shot.dataset.caption;imageDialog.showModal();}const install=event.target.closest('[data-install]');if(install)document.querySelector('#install-dialog').showModal();});
document.querySelectorAll('.image-dialog,.install-dialog').forEach(dialog=>{dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();}});});
const screens={
  studio:{number:'01',title:'Una toma.\nTodas tus fuentes.',description:'Elige qué quieres enseñar. Combina pantalla, cámara y micrófono desde un espacio pensado para grabar.',features:['Pantalla completa, ventana o un área','Webcam o cámara del teléfono','Micrófono y audio del sistema'],caption:'Estudio de Prisma: fuentes de pantalla, cámara y audio.'},
  appearance:{number:'02',title:'Que se vea\ncomo tú quieres.',description:'Dale tu toque a la grabación. Prepara el fondo, la calidad de la imagen y la forma de tu cámara antes de empezar.',features:['Hasta 1440p a 30 o 60 fps','Fondos con margen, sombra y esquinas suaves','Burbuja circular, cuadrada o 16:9'],caption:'Panel Aspecto de Prisma: calidad, fondos y burbuja de cámara.'},
  recording:{number:'03',title:'Pon el foco\nen lo importante.',description:'Acerca los detalles y guía la atención con tu cursor. Ajusta cómo se comporta el zoom y cómo comienza la toma.',features:['Zoom al clic y zoom manual','Resaltado de clics y duración ajustable','Cuenta atrás y carpeta de guardado'],caption:'Panel Grabación de Prisma: zoom, clics y guardado local.'},
  mobile:{number:'04',title:'Tu teléfono.\nTu nueva cámara.',description:'Crea un enlace, ábrelo en el móvil y conecta la cámara y la voz del teléfono a tu grabación.',features:['Cámara y micrófono por VDO.Ninja','Enlace nuevo en cada sesión','La pantalla sigue grabando si el móvil se desconecta'],caption:'Panel real del móvil de Prisma. Móvil desconectado en esta captura.'},
  transcript:{number:'05',title:'De tu voz\na tus subtítulos.',description:'Convierte la última toma o un archivo de vídeo en texto. El procesamiento se realiza en tu ordenador.',features:['Whisper integrado o Speaches local','Detección automática, español o inglés','Texto TXT y subtítulos SRT con marcas de tiempo'],caption:'Panel real de transcripción local de Prisma. Sin transcripción de demostración.'},
  shortcuts:{number:'06',title:'Más fluidez.\nMenos clics.',description:'Controla la grabación desde cualquier aplicación. Tus herramientas acompañan tu ritmo sin interrumpirlo.',features:['Grabar, pausar y silenciar','Mostrar widget y ajustar zoom','Controlar el guion y su velocidad'],caption:'Pantalla real de atajos globales y ayuda de Prisma.'}
};
const tabs=Array.from(document.querySelectorAll('[data-screen]'));
function selectScreen(tab,focus=false){const key=tab.dataset.screen,data=screens[key];tabs.forEach(button=>{const active=button===tab;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;});document.querySelector('#explorer-panel').setAttribute('aria-labelledby',tab.id);document.querySelector('#screen-number').textContent=data.number+' / 06';document.querySelector('#screen-title').innerText=data.title;document.querySelector('#screen-description').textContent=data.description;document.querySelector('#screen-features').replaceChildren(...data.features.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));const img=document.querySelector('#explorer-image'),button=document.querySelector('#explorer-shot');img.src='assets/screenshots/'+key+'.png';img.alt=data.caption;button.dataset.image=img.getAttribute('src');button.dataset.caption=data.caption;button.setAttribute('aria-label','Ampliar captura: '+tab.textContent.trim());if(focus){tab.focus();tab.scrollIntoView({block:'nearest',inline:'nearest'});}}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectScreen(tab));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();selectScreen(tabs[next],true);}});});
