'use strict';
(() => {
  const steps=[
    {id:'welcome',image:'studio-demo',title:'Tu próxima gran toma.',text:'Esto es Prisma: pantalla, cámara y voz en un estudio para Windows. Recorre sus herramientas con Siguiente y Anterior. El resaltado te muestra cada zona de la aplicación.',region:[102,199,882,517],side:'right'},
    {id:'sources',image:'studio',title:'Empieza por tus fuentes.',text:'Prisma permite elegir pantalla completa, una ventana o un área. Combina pantalla, cámara y micrófono, y añade el audio del PC.',region:[1030,212,312,215],side:'left'},
    {id:'mobile',image:'mobile',title:'Tu móvil también es tu cámara.',text:'Este panel crea un enlace de VDO.Ninja para conectar la cámara y el micro del teléfono. Se abre en el móvil y Prisma indica cuándo está listo. La captura muestra el móvil desconectado.',region:[1030,594,302,288],side:'left'},
    {id:'quality',image:'appearance',title:'Que se vea como tú quieres.',text:'La calidad se ajusta a 720p, 1080p o 1440p, con 30 o 60 fps. Los fondos añaden margen, esquinas suaves y sombra a la pantalla.',region:[1030,212,312,234],side:'left'},
    {id:'bubble',image:'appearance',title:'Tu cámara, en su sitio.',text:'La burbuja puede ser circular, cuadrada o en 16:9, con borde, tamaño y espejo ajustables. Se coloca arrastrándola en la vista previa. El zoom acerca la pantalla, no la cámara.',region:[1030,459,312,274],side:'left'},
    {id:'zoom',image:'recording',title:'Acerca lo que importa.',text:'El zoom puede seguir el cursor o activarse con un clic. El nivel y la duración se ajustan desde este panel, junto al resaltado de clics.',region:[1030,212,312,225],side:'left'},
    {id:'record',image:'studio-demo',title:'Graba. Respira. Continúa.',text:'La barra reúne grabación, pausa y reanudación. Prisma guarda en MP4 con FFmpeg o WebM sin él. Este recorrido muestra las herramientas con capturas reales y no inicia una grabación.',region:[102,785,881,64],side:'top'},
    {id:'widget',image:'widget-settings',title:'Todo a mano, en el widget.',text:'El widget permite grabar, pausar, silenciar y abrir el guion sin dejar la aplicación. Sus ajustes están sincronizados con el estudio. Ctrl + Shift + W lo muestra u oculta.',region:[0,0,840,104],size:[840,658],side:'bottom'},
    {id:'prompter',image:'teleprompter',title:'Tus palabras. Tu ritmo.',text:'El teleprompter muestra el guion con velocidad, tamaño y opacidad ajustables. Queda fuera del vídeo, igual que la ventana del estudio y el widget.',region:[0,0,600,52],size:[600,340],side:'bottom'},
    {id:'transcript',image:'transcript',title:'De la voz al texto.',text:'Whisper integrado o Speaches local transcriben la última toma o un archivo, tras preparar el motor. El resultado se copia como texto y se guarda en TXT o SRT con marcas de tiempo. El procesamiento se realiza en tu PC.',region:[102,213,881,147],side:'bottom'},
    {id:'shortcuts',image:'shortcuts',title:'Ya conoces tu nuevo estudio.',text:'Estos atajos funcionan desde cualquier aplicación. Prisma reúne cámara móvil, grabación, zoom, guion y transcripción, gratis para uso no comercial en Windows.',region:[102,220,881,326],side:'bottom'}
  ];
  const dialog=document.querySelector('#tour-dialog'),visual=document.querySelector('#tour-visual'),image=document.querySelector('#tour-image'),focus=document.querySelector('#tour-focus'),card=document.querySelector('#tour-card'),next=document.querySelector('#tour-next'),previous=document.querySelector('#tour-previous');
  let index=0,opener=null;
  const progress=document.querySelector('#tour-progress');
  steps.forEach((step,i)=>{const button=document.createElement('button');button.type='button';button.setAttribute('aria-label',`Paso ${i+1}: ${step.title}`);button.title=step.title;button.addEventListener('click',()=>showStep(i));progress.append(button);});
  function place(){if(!dialog.open)return;const step=steps[index],container=visual.getBoundingClientRect(),natural=step.size||[1360,900],scale=Math.min(container.width/natural[0],container.height/natural[1]),offsetX=(container.width-natural[0]*scale)/2,offsetY=(container.height-natural[1]*scale)/2;const region={x:offsetX+step.region[0]*scale,y:offsetY+step.region[1]*scale,width:step.region[2]*scale,height:step.region[3]*scale};Object.assign(focus.style,{left:region.x+'px',top:region.y+'px',width:region.width+'px',height:region.height+'px'});if(matchMedia('(min-width: 701px)').matches){const rect=card.getBoundingClientRect(),position=colocaTarjeta(region,{width:container.width,height:container.height},step.side,{width:rect.width,height:rect.height},18,14);Object.assign(card.style,{left:position.x+'px',top:position.y+'px'});card.dataset.side=position.lado;card.style.setProperty('--pointer',position.flecha+'px');}else{card.style.removeProperty('left');card.style.removeProperty('top');card.dataset.side='none';}}
  function showStep(newIndex){index=Math.max(0,Math.min(steps.length-1,newIndex));const step=steps[index];image.src=`assets/screenshots/${step.image}.png`;image.alt=`Prisma · ${step.title} Captura real de la aplicación.`;document.querySelector('#tour-counter').textContent=`PASO ${index+1} DE ${steps.length}`;document.querySelector('#tour-step-title').textContent=step.title;document.querySelector('#tour-step-text').textContent=step.text;previous.disabled=index===0;next.textContent=index===steps.length-1?'Terminar':'Siguiente';Array.from(progress.children).forEach((button,i)=>{button.classList.toggle('active',i===index);button.setAttribute('aria-current',i===index?'step':'false');});requestAnimationFrame(place);}
  function close(){if(document.fullscreenElement===dialog)document.exitFullscreen().catch(()=>{});dialog.close();}
  function advance(){if(index===steps.length-1)close();else showStep(index+1);}
  document.querySelectorAll('[data-tour-start]').forEach(button=>button.addEventListener('click',()=>{opener=button;dialog.showModal();document.body.classList.add('tour-open');showStep(0);next.focus();}));
  next.addEventListener('click',advance);previous.addEventListener('click',()=>showStep(index-1));
  document.querySelector('#tour-restart').addEventListener('click',()=>{showStep(0);next.focus();});
  document.querySelector('#tour-close').addEventListener('click',close);
  document.querySelector('#tour-fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement===dialog)await document.exitFullscreen();else if(dialog.requestFullscreen)await dialog.requestFullscreen();else dialog.classList.toggle('tour-max');}catch{dialog.classList.toggle('tour-max');}requestAnimationFrame(place);});
  dialog.addEventListener('close',()=>{document.body.classList.remove('tour-open');dialog.classList.remove('tour-max');opener?.focus();});
  dialog.addEventListener('cancel',()=>{if(document.fullscreenElement===dialog)document.exitFullscreen().catch(()=>{});});
  dialog.addEventListener('keydown',event=>{if(event.key==='ArrowRight'){event.preventDefault();advance();}if(event.key==='ArrowLeft'){event.preventDefault();showStep(index-1);}if(event.key==='Home'){event.preventDefault();showStep(0);}if(event.key==='End'){event.preventDefault();showStep(steps.length-1);}});
  image.addEventListener('load',place);new ResizeObserver(place).observe(visual);window.addEventListener('resize',place);document.addEventListener('fullscreenchange',()=>{const full=document.fullscreenElement===dialog;document.querySelector('#tour-fullscreen').setAttribute('aria-label',full?'Salir de pantalla completa':'Pantalla completa');requestAnimationFrame(place);});
})();
